<a href="https://colab.research.google.com/github/bdugick89/Data-Science-Bootcamp/blob/main/Copy_of_5a_Numpy_start.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

In [2]:
import numpy as np

## What is [Numpy]( https://en.wikipedia.org/wiki/NumPy )?

- A Python library written in Python and C
- Used for arrays and matrices
- More effecient than lists because every element is the **same data type**
- Some math functions - trig functions, random numbers, Boolean logic, etc.
- The basis for other data science libraries like Pandas


## Creating arrays

In [3]:
# Create an array using a list
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array([1,2,3,4,5])
type(arr)

In [4]:
# Create an array using range()
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Your Turn
Create a numpy array of the numbers 1 - 8 using:
1. A list
2. The `range()` function

In [5]:
# Solution
arr1 = np.array([12,123,143123,42341,])

In [8]:
# Solution
np.array(range(12121))

array([    0,     1,     2, ..., 12118, 12119, 12120])

## Create Special Types of Arrays

In [9]:
# Create an array of zeros
np.zeros(15)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# Create an array of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones(5)*7

array([7., 7., 7., 7., 7.])

In [12]:
# Create an array (of length 10) full of 7's
np.full(10, 7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [13]:
np.full(10, 1.0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
# Create an array from 0 to 29 incremented by 3s
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [15]:
# Create an array of 5 equally spaced numbers from 0 to 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Your Turn
1. Create an array of the numbers 0 to 20 incremented by 2s. Save it to a variable called `evens`. Print out `evens`.
2. Create the following array `array([0., 0.33333, 0.6666, 1.])`.

In [22]:
# Solution
even=np.arange(0,21,2)

In [23]:
# Solution
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

## Two Dimensional Arrays

In [24]:
# Create an array using a list of lists
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
# Create an array using a for loop
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [31]:
# Create a 2-dimensional array of ones
np.ones((4,5))


SyntaxError: unmatched ')' (<ipython-input-31-73d3a305d220>, line 4)

In [29]:
# Create a 2-dimensional array filled with 7's
np.full((4,5), 7)
np.full((4,5\), )

TypeError: full() missing 1 required positional argument: 'fill_value'

In [32]:
np.ones((4,5))*7

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

### Your Turn
1. Create a 2x2 array filled with the word "HI".
2. Create the a 3x3 array with 1's in the first row, 2's in the second row, and 3's in the third row.

In [33]:
# Solution
np.full((2, 2), "HI")

array([['HI', 'HI'],
       ['HI', 'HI']], dtype='<U2')

In [42]:
# Solution
np.array([range(,2) for i in [1,2,3]])

np.array([[1,1,1,],[2,2,2],[3,3,3]])
np.full((3,3),[1,2,3]).transpose()
np.array([(i,)*3 for in [1,2,3]])

SyntaxError: invalid syntax (<ipython-input-42-5f00e7d9ba47>, line 1)

## Generating Random Numbers

In [43]:
# Generate 10 random numbers from 0 to 1
np.random.random(10)

array([0.2037886 , 0.49748816, 0.33052432, 0.27476243, 0.36514694,
       0.38447635, 0.43606761, 0.59439012, 0.01968829, 0.42464305])

In [44]:
# Generate 10 random numbers from a normal distribution with mean 0 and
# standard deviation of 1
np.random.normal(0,1,10)

array([ 0.69412306, -0.71684504, -0.43147152, -0.52373609,  0.00750794,
       -0.59285394, -1.1616274 ,  1.11350729,  1.76197288, -0.23368811])

In [45]:
# Generate a 3x3 matrix of random numbers from a normal distribution with
# mean 0 and standard deviation 1
np.random.normal(0, 1, (3,3))

array([[ 0.6377883 ,  0.68799389, -1.48919187],
       [ 1.39594757,  0.29642764, -0.67331509],
       [-0.78571983,  0.86715446, -0.29141591]])

In [46]:
# Generate a 3x3 matrix of random integers from 0 to 9
np.random.randint(0, 10, (3,3))

array([[7, 9, 0],
       [2, 9, 9],
       [8, 5, 2]])

In [47]:
# Setting the seed for repeatability
np.random.seed(42)
np.random.randint(0, 10, 3)

array([6, 3, 7])

### Your Turn
Generate 10 random numbers from the **lognormal** distribution with a mean 0 and standard deviation of 1.

In [48]:
# Solution
(mean=mean, stddev=sigma, shape=size) = (1.0,1.0,10)
np.random.lognormal(mean=1.0,sigma=1.0, size=10)

np.random.lognormal
(mean=mean,
 sigma=stddev,
 size=shape)

array([0.89415144, 3.73931405, 3.59319325, 7.46716407, 1.52062566,
       1.60774117, 1.53513732, 1.0788732 , 0.19937875, 7.03128644])

## dtypes

All elements of the array must be the same data type.  

In [49]:
arr = np.random.randint(0, 10, (3,3))
print(arr.dtype)
print(arr)

int64
[[0 9 2]
 [6 3 8]
 [2 4 2]]


In [50]:
arr[0,0] = 2.2
print(arr)

[[2 9 2]
 [6 3 8]
 [2 4 2]]


It will 'upcast' if needed.  
- In this example since we have one float, the integers are upcast to floats too

In [51]:
arr = np.array([1,2,3,4,5,6.2])
print(arr.dtype, arr)

float64 [1.  2.  3.  4.  5.  6.2]


We can also specify the datatype.

In [52]:
arr = np.array([1,2,3,4,5], dtype='float16')
arr.dtype

dtype('float16')

In [53]:
arr

array([1., 2., 3., 4., 5.], dtype=float16)

In [54]:
arr = np.array([1,2,3,4,5], dtype='float')
arr.dtype

dtype('float64')

### Your Turn
Create an array of the numbers 0 - 10. Save it to a variable called `my_array`. Then change the 1 in your array to be equal to 1.4. Print out `my_array`.

In [63]:
# Solution
my_array=np.array([1,2,3,4,5,6,7,8,9,10])
index_to_update = np.where(my_array == 1)
my_array[index_to_update] = 1.4
my_array



my_array = np.arange(10, dtype=float)
print(my_array)


my_array[1]=1.4

TypeError: arange() got an unexpected keyword argument 'dytpe'

## Array Attrributes

What are attributes?
- values associated with an object
- accessed by object.attribute (like methods but without the ())
- lots of objects have attributes

In [66]:
arr1 = np.random.randint(10, size = 9)
arr2 = np.random.randint(10, size=(5,7))

print(arr1)
print(arr2)
#data type
print(arr1.dtype)
print(arr2.dtype)
#number of dimensions
print(arr1.ndim)
print(arr2.ndim)
#shape (the size of each dimension)
print(arr1.shape)
print(arr2.shape)

[0 8 6 8 7 0 7 7 2]
[[0 7 2 2 0 4 9]
 [6 9 8 6 8 7 1]
 [0 6 6 7 4 2 7]
 [5 2 0 2 4 2 0]
 [4 9 6 6 8 9 9]]
int64
int64
1
2
(9,)
(5, 7)


### Your Turn
1. What does the size attribute do?
2. Find the size of `arr1` and `arr2`.

1. Solution



In [67]:
# Solution
print(arr1.shape)
help(np.ndarray.size)

(9,)
Help on getset descriptor numpy.ndarray.size:

size
    Number of elements in the array.
    
    Equal to ``np.prod(a.shape)``, i.e., the product of the array's
    dimensions.
    
    Notes
    -----
    `a.size` returns a standard arbitrary precision Python integer. This
    may not be the case with other methods of obtaining the same value
    (like the suggested ``np.prod(a.shape)``, which returns an instance
    of ``np.int_``), and may be relevant if the value is used further in
    calculations that may overflow a fixed size integer type.
    
    Examples
    --------
    >>> x = np.zeros((3, 5, 2), dtype=np.complex128)
    >>> x.size
    30
    >>> np.prod(x.shape)
    30



In [68]:
# Solution
arr1.size,arr2.size

(9, 35)

## Array Indexing

One dimensional arrays - square brackets, starting at 0 (just like lists)

In [ ]:
arr = np.random.randint(10, size = 9)
print(arr)
print(arr[0])
print(arr[8])

In [ ]:
arr[-1]

Two dimensional arrays - square brackets, starting at 0, comma-separated tuple of indices

In [ ]:
arr = np.random.randint(10, size = (5,4))

print(arr)
print(arr[2,3]) #[row, column]

### Your Turn
1. Create an array of 11 equally spaced points from 1 to 5. Save it to a variable called `one_to_five_array`.
2. Use indexing to pull out the `3`.

In [82]:
# Solution
one_to_five_array = np.random.randint(11, size = (11,5))

print(one_to_five_array)
print(one_to_five_array[4,1]) #[row, column]


 one_to_five_array= np.linspace(1,5,11)
 one_to_five_array
 one_to_five_array[5]




array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [ ]:
# Solution


## Slicing Arrays

Note: Default is to return views and not copies


One dimensional

In [83]:
a=5
b=a
c=5

print(a, b, c)
a=7
print(a, b, c)


5 5 5
7 5 5


In [89]:
# Using lists to demonstrate "view" and "copy" concept
a=np.array([1,2,3,4,5])
b=a
c=a.copy()
print("Before ...")
print(f"a: {a}")
print(f"b: {b}")
print(f"c: {c}")
a[1]=8
print("After ...")
print(f"a: {a}")
print(f"b: {b}")
print(f"c: {c}")


Before ...
a: [1 2 3 4 5]
b: [1 2 3 4 5]
c: [1 2 3 4 5]
After ...
a: [1 8 3 4 5]
b: [1 8 3 4 5]
c: [1 2 3 4 5]


In [90]:
b[3]=23
print(a)
print(b)
print(c)

[ 1  8  3 23  5]
[ 1  8  3 23  5]
[1 2 3 4 5]


In [91]:
arr = np.random.randint(10, size = 9)
print(arr)

[6 9 2 6 9 8 3 0 1]


In [92]:
# What happens if we don't copy?
arr2 = arr
arr3 = arr.copy()
print(f"arr: {arr}")
print(f"arr2: {arr2}")
print(f"arr3: {arr3}")
arr[0] = 10
print(f"arr (updated): {arr}")
print(f"arr2 (without copying): {arr2}")
print(f"arr3 (with copying): {arr3}")

arr: [6 9 2 6 9 8 3 0 1]
arr2: [6 9 2 6 9 8 3 0 1]
arr3: [6 9 2 6 9 8 3 0 1]
arr (updated): [10  9  2  6  9  8  3  0  1]
arr2 (without copying): [10  9  2  6  9  8  3  0  1]
arr3 (with copying): [6 9 2 6 9 8 3 0 1]


In [ ]:
arr

In [93]:
print(arr[:7]) #[start:stop:increment]
print(arr[4:])
print(arr[4:7])
print(arr[4:7:2])
print(arr[4:1:-1])
print(arr[-5:1:-1])

[10  9  2  6  9  8  3]
[9 8 3 0 1]
[9 8 3]
[9 3]
[9 6 2]
[9 6 2]


### Your Turn
1. Create an 10-element array full of zeros. Assign it to a variable called `zero_array`.
2. Make a copy of `zero_array` and save it as `zero_array_copy`.
3. Use slicing to pull out the first 3 elements of `zero_array_copy`.

In [97]:
#Solution

zero_array = np.zeroes(10)
zero_array
zero_array = zero_array.copy()

zero_array[-3:]

AttributeError: module 'numpy' has no attribute 'zeroes'

In [ ]:
# Solution


In [ ]:
# Solution


Two dimensional

In [98]:
arr = np.random.randint(10, size = (5,4))
print(arr, '\n')
print(arr[2:4, 0:3]) #[row, column]
print(arr)

[[0 4 4 6]
 [8 8 2 2]
 [2 3 7 5]
 [7 0 7 3]
 [0 7 3 5]] 

[[2 3 7]
 [7 0 7]]
[[0 4 4 6]
 [8 8 2 2]
 [2 3 7 5]
 [7 0 7 3]
 [0 7 3 5]]


In [ ]:
arr

In [ ]:
# pull first two columns of an array
print(arr[:,0:2])

In [ ]:
arr[0,:]

### Your Turn
1. Create a 3x3 array filled with random numbers from a normal distribution with mean 0 and standard deviation 1. Save it to a variable called `normal_array`.
2. Pull out the first row of `normal_array`.

In [ ]:
# Solution


In [ ]:
# Solution


## Reshaping of Arrays


In [ ]:
np.arange?

In [99]:
arr = np.arange(9)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr.shape

In [ ]:
arr = arr.reshape((3,3))
print(arr)
print(arr.reshape(9))

In [ ]:
arr

In [ ]:
arr.flatten()

In [122]:
#(#np.arange(3*3*3)
#reshape((3,3,3))
#.flatten())

shape=(6,3)
size=np.prod(shape)
Fill=[0]*size
np.concatenate([arange(0,13),np.array(fill)])[:15].reshape(5.3)
#np.arange(13).reshape(13,1)



NameError: name 'arange' is not defined

### Your Turn
1. Create a 3x3 array full of ones. Assign it to a variable called `ones_matrix`.
2. Flatten the array. Assign it to a variable called `ones_array`. Print out `ones_array`.

In [134]:
# Solution
#ones_matrix = np.ones((3, 3))
#one_matrix = np.random.randint(1, size = (3,3))
normal_array = np.random.normal(loc = 0, scale = 1.0, size = (3,3))
print(normal_array, '\n')

normal_array[0,:]



np.random.normal?



ones_matrix = np.ones((3, 3))
ones_array =ones_matrix.flatten()
ones_array



ones_array =ones_matrix.reshape(1,1,-1)
ones_array


array([[[1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [125]:
# Solution


##Joining and Splitting Arrays

In [135]:
arr1 = np.array([[1,1,1],[2,2,2]])
arr2 = np.array([[3,3,3],[4,4,4]])
print(arr1)
print('')
print(arr2)

[[1 1 1]
 [2 2 2]]

[[3 3 3]
 [4 4 4]]


In [136]:
#default is to concatenate along the first axis (axis=0) - add rows
arr3 = np.concatenate([arr1, arr2])
print(arr3)


[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [137]:
#can specify to concatenate alond second axis (0 indexing) - add columns
arr4 = np.concatenate([arr1,arr2], axis=1)
print(arr4)


[[1 1 1 3 3 3]
 [2 2 2 4 4 4]]


In [ ]:
arr1[:,0:2]

In [ ]:
arr1[:,0:2].transpose()

In [ ]:
arr1[:,2:]

In [ ]:
arr2

In [ ]:
np.concatenate([arr1[:,0:2].transpose(),
                arr2,
                arr1[:,2:],
                arr2],
    axis=1)

### Your Turn
1. Create a 2x2 array filled with ones. Save it as `ones_array`.
2. Create a 2x2 array filled with zeros. Save it as `zeros_array`.
3. Concatenate `ones_array` and `zeros_array` along the first axis (adding more rows).

In [144]:
# Solution
ones_array = np.ones((2, 2))
zeros_array= np.zeros((2, 2))
zeros_array
np.concatenate([ones_array,zeros_array], axis=1)


ones_array = no.full((2,2),1)
zeros_array = np.zeros((2,2), dtype = int)

np.concatenate((one_array,zeros_array,)axis=o)

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.]])

In [ ]:
# Solution


In [ ]:
# Solution


## Ufuncs
Ufunc is a function that operates on ndarrays in an element-by-element manner.

U is for:

- Universal


In [145]:
arr = np.arange(9).reshape((3,3))
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [146]:
print(arr+5)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [147]:
print(arr/5)

[[0.  0.2 0.4]
 [0.6 0.8 1. ]
 [1.2 1.4 1.6]]


In [148]:
print(3**arr)

[[   1    3    9]
 [  27   81  243]
 [ 729 2187 6561]]


In [149]:
print(arr**3)

[[  0   1   8]
 [ 27  64 125]
 [216 343 512]]


## Aggregate Functions

In [153]:
# Sum across all elements
print(arr)
print(np.sum(arr))  # function
print(arr.sum())   # method
print(8*(8+1)//2)  # n(n+1)/2 = sum of a seres of number from 0

[[0 1 2]
 [3 4 5]
 [6 7 8]]
36
36
36


In [154]:
# Find the minimum
np.min(arr)  # function
arr.min()    # method

0

In [155]:
# Find the maximum
np.max(arr)  # function
arr.max()    # method

8

In [ ]:
# Calculate the mean
np.mean(arr)  # function
arr.mean()    # method

In [ ]:
# Find the median
np.median(arr)  # function
# arr.median()    # method

In [ ]:
# use a list as an argument
mylist = [1,2,3]
np.mean(mylist)

In [ ]:
# arr.a

### Your Turn
1. Create a 100-element array filled with random numbers from a normal distribution with mean 10 and standard deviation 1. Save it as `random_array`.
2. Find the min, max, mean, and standard deviation of your array.

In [165]:
# Solution

np.random.seed(42)
random_array = np.random.normal(loc = 10, scale = 1.0, size = (100))
np.min(random_array)  # function
random_array.max()
random_array.std()


#concats the functional with the result
k= "min, max,mean,stdev".split(",")
dict(zip(k,(r.min())

7.380254895910255

## Boolean Arrays

In [166]:
np.random.seed(42)
arr = np.random.randint(10, size=(4,5))
print(arr)
print("\n")
print(arr < 3)

[[6 3 7 4 6]
 [9 2 6 7 4]
 [3 7 7 2 5]
 [4 1 7 5 1]]


[[False False False False False]
 [False  True False False False]
 [False False False  True False]
 [False  True False False  True]]


In [ ]:
# Solution


In [167]:
# filtering
arr[arr<3]

array([2, 2, 1, 1])

In [168]:
(arr<3)*1

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 1]])

In [169]:
# count of elements that meet a condition
np.count_nonzero(arr<3)


4

In [ ]:
# count of elements that meet a condition
np.sum(arr<3)

In [171]:
(arr<3).sum()

4

In [170]:
# proportion that meets a conditions
(arr < 3).mean()


0.2

Boolean Masks - Boolean Indexing

In [ ]:
mask = (arr < 3)
print(arr)
print("")
print(mask)
print("")
arr*mask

In [ ]:
arr*(arr < 4)

For logical AND and OR, use `&` or `|` (NOT and, or)

In [172]:
arr*((arr % 2 == 0) & (arr >= 6))

array([[6, 0, 0, 0, 6],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [173]:
mask = np.logical_and((arr % 2 == 0),(arr >= 6))
arr*mask

array([[6, 0, 0, 0, 6],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
mask = (arr % 2 == 0) | (arr >= 6)
print((arr*mask)*100)
print("")
filter = mask
print((arr[filter])*100)


In [ ]:
arr*((arr % 2 == 0) | (arr >= 6))

In [ ]:
mask = np.logical_or((arr % 2 == 0), (arr >= 6))
arr*mask

In [ ]:
# np.logical

Logical XOR

In [ ]:
arr*((arr % 2 == 0) ^ (arr >= 6))

Logical NOT

In [ ]:
arr

In [ ]:
arr*(arr >= 6)

In [ ]:
np.logical_not(arr*(arr >= 6))


### Your Turn
1. Create an 20 element array with random integers from 0 to 20. Assign it to a variable called `my_array`.
2. Use boolean indexing to return the values of the array that are greater than 10.
3. Use boolean indexing to return the values of the array that are less than 3 or greater than 15.

Feel free to use either filtering, masking, or both.

In [182]:
# Solution
np.random.seed(42)
random_array = np.random.randint(0, 20, size=20)
random_array

array([ 6, 19, 14, 10,  7,  6, 18, 10, 10,  3,  7,  2,  1, 11,  5,  1,  0,
       11, 11, 16])

In [177]:
# Solution
random_array[random_array>10]

array([11, 11, 16, 15, 14, 14, 18, 11, 19, 18, 17, 13])

In [179]:
# Solution
random_array[(random_array < 3) | (random_array > 15)]


array([ 0, 16, 18, 19,  2, 18, 17])