<a href="https://colab.research.google.com/github/bdugick89/Data-Science-Bootcamp/blob/main/5a_Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Playing with NumPY

## Setup: Import numpy

In [1]:
import numpy as np

## Problem 1: random integers



### Part 1


Create a 1 dimensional array with 10 random integers

In [27]:
array1=np.arange(0,30,3)
array1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

### Part 2


Create a second 1 dimensional array with 10 random integers.  Concatenate it with your first array to create a 2 dimensional array with shape (2,10).

**Note:**  You may have to get creative to make this work.  

In [26]:
array2=np.random.rand(10)
array2


array([0.19234587, 0.08790802, 0.13737769, 0.38798553, 0.20719018,
       0.49473803, 0.01507793, 0.06951904, 0.81821959, 0.59142278])

In [30]:
concatenated_array = np.concatenate((array1, array2), axis=0)
concatenated_array

array([0.00000000e+00, 3.00000000e+00, 6.00000000e+00, 9.00000000e+00,
       1.20000000e+01, 1.50000000e+01, 1.80000000e+01, 2.10000000e+01,
       2.40000000e+01, 2.70000000e+01, 1.92345874e-01, 8.79080224e-02,
       1.37377690e-01, 3.87985525e-01, 2.07190177e-01, 4.94738030e-01,
       1.50779302e-02, 6.95190446e-02, 8.18219593e-01, 5.91422777e-01])

### Part 3


Use indexing to access the first two columns in the array you created in #2.

In [36]:
concatenated_array[:2]

array([0., 3.])

## Problem 2: 2D array



Convert the array below into a 2 dimensional array


```python
arr = np.arange(70)
```

In [49]:
arr = np.arange(70)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69])

In [50]:
two_d_array = arr.reshape(7, 10)


In [51]:
num_dimensions = two_d_array.ndim

print("Number of dimensions:", num_dimensions)


Number of dimensions: 2


## Problem 3: multiply


Multiply all numbers in the array below by a number of your choice.  

```python
arr = np.arange(30)
```

In [52]:
arr = np.arange(30)


In [53]:
print(1231231**arr)

[                   1              1231231        1515929775361
  1866459733247499391  3047355537111013889  4647696502781079423
  5086966137482708737  7389072368900784767 -2514158363084278783
  1513982432787305855   169310723474809089 -6043402378973353857
  1909058332973534721  7670493267061160831  6425768048389372673
  -799042720177484161 -4412467766194247679  1943653163991916927
  8366816665448355073 -7944426086887312257  -736811715194011135
  7001890924515166079  6895986163175288577 -4742110116430554497
  1326239123266739201   936574061064138111 -3847757671660074751
 -4159569692159278977 -3147718904689428991  -398573662099254401]


## Problem 4: stats


Find the min, max, and mean and standard deviation for the array below.

```python
arr = np.random.normal(5,10,10000)
```


In [54]:
arr = np.random.normal(5,10,10000)


In [55]:
arr.mean()


4.927477440973822

In [56]:
arr.min()


-31.31253335674679

In [57]:
arr.max()

42.89867767022286

## Problem 5: filtering


### Part 1


Create a 4X6 array with random integers between 0 and 10.  


In [62]:
fourxsix = np.random.randint(0, 10, (4,6))
fourxsix

array([[6, 2, 3, 1, 4, 7],
       [5, 9, 9, 0, 1, 1],
       [0, 3, 2, 3, 8, 3],
       [9, 8, 9, 7, 0, 8]])

### Part 2


Create a boolean array with `True` entries where the entries in your array are greater than 6


In [65]:
filter = (fourxsix > 6)
filter


array([[6, 2, 3, 1, 4, 7],
       [5, 9, 9, 0, 1, 1],
       [0, 3, 2, 3, 8, 3],
       [9, 8, 9, 7, 0, 8]])

### Part 3


Use your boolean array as a filter to pull out the entries greater than 6

In [66]:
fourxsix[filter]

array([7, 9, 9, 8, 9, 8, 9, 7, 8])